### ISSUE TITLE
`getAccountInfo()` Fails In 0.1.199 and Above

### ISSUE THREAD

**Issue by reynoldsalec** [platformsh/platformsh-client-js#219]
@gilzow and I have been trying to resolve a [bug with the Platform.sh Lando integration](https://github.com/lando/platformsh/issues/184), where upon running a `lando init`, we are unable to retrieve the user's project list via the `getAccountInfo()` function provided by `platformsh-client-js`.

Specifically the line that produces the ultimate error in Lando is https://github.com/lando/platformsh/blob/main/recipes/platformsh/init.js#L35

While trying different versions of `platformsh-client`, I did notice a change in behavior between `0.1.198` and `0.1.199` of `platformsh-client-js`; both versions fail to produce the project list, but on `0.1.198` no explicit error is produced (the process just seems to hang). It looks like the underlying function powering `getAccountInfo()` changed, as did the version of `isomorphic-fetch`...perhaps one of these changes might have produced this error? https://github.com/platformsh/platformsh-client-js/compare/v0.1.198...v0.1.199

Hoping that your finely tuned eyes notice something I haven't, happy to jump on a screenshare if that's easier, should be able to ping me via Slack if you join the `#lando-platformsh` shared channel.

**Comment by rfay** [comment]
@gilzow could you please follow up here, and maybe we can figure out what's wrong here, and why it's not being caught by automated tests? Who would be the responsible person to assign this to?

**Comment by gilzow** [comment]
0.1.199 was [released](https://github.com/platformsh/platformsh-client-js/releases/tag/v0.1.199) almost a year ago. @reynoldsalec have you tried updating the client to a more recent version? Is the error still present with a newer version of the client?

**Comment by reynoldsalec** [comment]
@gilzow yep, currently packaged version since the last release (December 12th) was `0.1.217`: https://github.com/lando/platformsh/blob/main/yarn.lock#L3915

The reason I brought up `0.1.199` in particular is because the change in behavior I noticed when running all the versions trying to find an older version than `0.1.217` that would work.

**Comment by gilzow** [comment]
Gotcha. Just wanted to clarify.

@tlattimore / @shakaman - any ideas on what might be causing the issue above?

**Comment by tlattimore** [comment]
I will investigate this further but I can confirm the issue was introduced with the isomorphic-fetch bump in `0.1.199`. The issue we are seeing has been reported by others at https://github.com/matthew-andrews/isomorphic-fetch/issues/194. If anything, we can investigate moving away from isomorphic-fetch altogether.

**Comment by tlattimore** [comment]
@reynoldsalec regarding, 

> The reason I brought up `0.1.199` in particular is because the change in behavior I noticed when running all the versions trying to find an older version than `0.1.217` that would work.

Is it reasonable to assume it is just at version `0.1.217` is because that's the last time `yarn install` was run? I ask just to verify and check there isn't another reason you're at that version.

**Comment by reynoldsalec** [comment]
Exactly @tlattimore, that was the last time `yarn install` was run when the release was packaged up.

Good to hear RE: `isomorphis-fetch`...that was my suspicion based on "what changed" in those modules, but good catch with that issue. I'll dig into that and see if there's anything clever we can do to adapt in the short term.

Do you have any plans to move away from `isomorphic-fetch`?

**Comment by tlattimore** [comment]
I have started working [this branch]( https://github.com/platformsh/platformsh-client-js/pull/new/219-fix-fetch) to test moving away from it `isomorphic-fetch`. Will be testing a bit more before we move forward with that.

**Comment by reynoldsalec** [comment]
Awesome, thanks @tlattimore, that is huge.

**Comment by gilzow** [comment]
@tlattimore has there been any updates to your branch you're working on? This issue is a pretty substantial road black for platform.sh customers who are using lando for their local development.

**Comment by tlattimore** [comment]
Hey @gilzow, this should now be resolved with `0.1.230` which is now available on npm.

**Comment by gilzow** [comment]
@tlattimore PERFECT! Thank you! 
@reynoldsalec Can you try updating the lando platform plugin with this latest version and see if this corrects the issue? Thanks!

**Comment by reynoldsalec** [comment]
Awesome @tlattimore, I'll try updating this later today or tomorrow, thanks for the great work!

**Comment by reynoldsalec** [comment]
I think this resolved the issue...was still having a problem when trying with my account, but after refreshing my token it worked perfectly. [Relevant tests](https://github.com/lando/platformsh/actions/runs/4759923449/jobs/8459684749?pr=188) seem to pass.

Going to roll this into our next Lando release, thanks again @tlattimore for your help and @gilzow + @rfay!
